In [37]:
#Imports
import pandas as pd
import numpy as np

In [38]:
# Load the csv files
people_df = pd.read_csv('LDS24 - Data/People.csv')
crashes_df = pd.read_csv('LDS24 - Data/Crashes.csv')
vehicles_df = pd.read_csv('LDS24 - Data/Vehicles.csv')

In [39]:
# Exploration of "People" dataframe

# Print information
print('Info')
people_df.info()


#Print columns
print('Columns')
print(people_df.columns)

#Print shape
print('Shape')
print(people_df.shape)

#Check missing values
print('Missing values')
print(people_df.isna().sum())

columns_with_missing_values = people_df.columns[people_df.isnull().any()].tolist()
print('Columns with missing values')
print(columns_with_missing_values)

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564565 entries, 0 to 564564
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   PERSON_ID              564565 non-null  object
 1   PERSON_TYPE            564565 non-null  object
 2   RD_NO                  564565 non-null  object
 3   VEHICLE_ID             553869 non-null  float64
 4   CRASH_DATE             564565 non-null  object
 5   CITY                   420645 non-null  object
 6   STATE                  422589 non-null  object
 7   SEX                    557411 non-null  object
 8   AGE                    403584 non-null  float64
 9   SAFETY_EQUIPMENT       563155 non-null  object
 10  AIRBAG_DEPLOYED        554113 non-null  object
 11  EJECTION               557860 non-null  object
 12  INJURY_CLASSIFICATION  564269 non-null  object
 13  DRIVER_ACTION          454799 non-null  object
 14  DRIVER_VISION          454681 non-null  object
 15  PHYSICAL_CONDITION     455064 non-null  object
 16  BAC_RESULT             455732 non-null  object
 17  DAMAGE_CATEGORY        564565 non-null  object
 18  DAMAGE                 490256 non-null  float64
dtypes: float64(3), object(16)
memory usage: 81.8+ MB
Columns
Index(['PERSON_ID', 'PERSON_TYPE', 'RD_NO', 'VEHICLE_ID', 'CRASH_DATE', 'CITY',
       'STATE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'AIRBAG_DEPLOYED',
       'EJECTION', 'INJURY_CLASSIFICATION', 'DRIVER_ACTION', 'DRIVER_VISION',
       'PHYSICAL_CONDITION', 'BAC_RESULT', 'DAMAGE_CATEGORY', 'DAMAGE'],
      dtype='object')
Shape
(564565, 19)
Missing values
PERSON_ID                     0
PERSON_TYPE                   0
RD_NO                         0
VEHICLE_ID                10696
CRASH_DATE                    0
CITY                     143920
STATE                    141976
SEX                        7154
AGE                      160981
SAFETY_EQUIPMENT           1410
AIRBAG_DEPLOYED           10452
EJECTION                   6705
INJURY_CLASSIFICATION       296
DRIVER_ACTION            109766
DRIVER_VISION            109884
PHYSICAL_CONDITION       109501
BAC_RESULT               108833
DAMAGE_CATEGORY               0
DAMAGE                    74309
dtype: int64
Columns with missing values
['VEHICLE_ID', 'CITY', 'STATE', 'SEX', 'AGE', 'SAFETY_EQUIPMENT', 'AIRBAG_DEPLOYED', 'EJECTION', 'INJURY_CLASSIFICATION', 'DRIVER_ACTION', 'DRIVER_VISION', 'PHYSICAL_CONDITION', 'BAC_RESULT', 'DAMAGE']

In [42]:
# Exploration of "Vehicles" dataframe

# Print information
print('Info')
vehicles_df.info()


#Print columns
print('Columns')
print(vehicles_df.columns)

#Print shape
print('Shape')
print(vehicles_df.shape)

#Check missing values
print('Missing values')
print(vehicles_df.isna().sum())

vehicles_columns_with_missing_values = vehicles_df.columns[vehicles_df.isnull().any()].tolist()
print('Columns with missing values')
print(vehicles_columns_with_missing_values)

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460437 entries, 0 to 460436
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   CRASH_UNIT_ID        460437 non-null  int64
 1   RD_NO                460437 non-null  object
 2   CRASH_DATE           460437 non-null  object
 3   UNIT_NO              460437 non-null  int64
 4   UNIT_TYPE            460436 non-null  object
 5   VEHICLE_ID           450064 non-null  float64
 6   MAKE                 450064 non-null  object
 7   MODEL                448651 non-null  object
 8   LIC_PLATE_STATE      410808 non-null  object
 9   VEHICLE_YEAR         371782 non-null  float64
 10  VEHICLE_DEFECT       450064 non-null  object
 11  VEHICLE_TYPE         450064 non-null  object
 12  VEHICLE_USE          450064 non-null  object
 13  TRAVEL_DIRECTION     450064 non-null  object
 14  MANEUVER             450064 non-null  object
 15  OCCUPANT_CNT         450064 non-null  float64
 16  FIRST_CONTACT_POINT  450049 non-null  object
dtypes: float64(3), int64(2), object(12)
memory usage: 59.7+ MB
Columns
Index(['CRASH_UNIT_ID', 'RD_NO', 'CRASH_DATE', 'UNIT_NO', 'UNIT_TYPE',
       'VEHICLE_ID', 'MAKE', 'MODEL', 'LIC_PLATE_STATE', 'VEHICLE_YEAR',
       'VEHICLE_DEFECT', 'VEHICLE_TYPE', 'VEHICLE_USE', 'TRAVEL_DIRECTION',
       'MANEUVER', 'OCCUPANT_CNT', 'FIRST_CONTACT_POINT'],
      dtype='object')
Shape
(460437, 17)
Missing values
CRASH_UNIT_ID              0
RD_NO                      0
CRASH_DATE                 0
UNIT_NO                    0
UNIT_TYPE                  1
VEHICLE_ID             10373
MAKE                   10373
MODEL                  11786
LIC_PLATE_STATE        49629
VEHICLE_YEAR           88655
VEHICLE_DEFECT         10373
VEHICLE_TYPE           10373
VEHICLE_USE            10373
TRAVEL_DIRECTION       10373
MANEUVER               10373
OCCUPANT_CNT           10373
FIRST_CONTACT_POINT    10388
dtype: int64
Columns with missing values
['UNIT_TYPE', 'VEHICLE_ID', 'MAKE', 'MODEL', 'LIC_PLATE_STATE', 'VEHICLE_YEAR', 'VEHICLE_DEFECT', 'VEHICLE_TYPE', 'VEHICLE_USE', 'TRAVEL_DIRECTION', 'MANEUVER', 'OCCUPANT_CNT', 'FIRST_CONTACT_POINT']

In [43]:
# Exploration of "Crashes" dataframe

# Print information
print('Info')
crashes_df.info()


#Print columns
print('Columns')
print(crashes_df.columns)

#Print shape
print('Shape')
print(crashes_df.shape)

#Check missing values
print('Missing values')
print(crashes_df.isna().sum())

crashes_columns_with_missing_values = crashes_df.columns[crashes_df.isnull().any()].tolist()
print('Columns with missing values')
print(crashes_columns_with_missing_values)

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257925 entries, 0 to 257924
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   RD_NO                          257925 non-null  object
 1   CRASH_DATE                     257925 non-null  object
 2   POSTED_SPEED_LIMIT             257925 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE         257925 non-null  object
 4   DEVICE_CONDITION               257925 non-null  object
 5   WEATHER_CONDITION              257925 non-null  object
 6   LIGHTING_CONDITION             257925 non-null  object
 7   FIRST_CRASH_TYPE               257925 non-null  object
 8   TRAFFICWAY_TYPE                257925 non-null  object
 9   ALIGNMENT                      257925 non-null  object
 10  ROADWAY_SURFACE_COND           257925 non-null  object
 11  ROAD_DEFECT                    257925 non-null  object
 12  REPORT_TYPE                    252929 non-null  object
 13  CRASH_TYPE                     257925 non-null  object
 14  DATE_POLICE_NOTIFIED           257925 non-null  object
 15  PRIM_CONTRIBUTORY_CAUSE        257925 non-null  object
 16  SEC_CONTRIBUTORY_CAUSE         257925 non-null  object
 17  STREET_NO                      257925 non-null  int64
 18  STREET_DIRECTION               257923 non-null  object
 19  STREET_NAME                    257924 non-null  object
 20  BEAT_OF_OCCURRENCE             257921 non-null  float64
 21  NUM_UNITS                      257925 non-null  float64
 22  MOST_SEVERE_INJURY             257918 non-null  object
 23  INJURIES_TOTAL                 257925 non-null  float64
 24  INJURIES_FATAL                 257925 non-null  float64
 25  INJURIES_INCAPACITATING        257925 non-null  float64
 26  INJURIES_NON_INCAPACITATING    257925 non-null  float64
 27  INJURIES_REPORTED_NOT_EVIDENT  257925 non-null  float64
 28  INJURIES_NO_INDICATION         257925 non-null  float64
 29  INJURIES_UNKNOWN               257925 non-null  float64
 30  CRASH_HOUR                     257925 non-null  int64
 31  CRASH_DAY_OF_WEEK              257925 non-null  int64
 32  CRASH_MONTH                    257925 non-null  int64
 33  LATITUDE                       256903 non-null  float64
 34  LONGITUDE                      256903 non-null  float64
 35  LOCATION                       256903 non-null  object
dtypes: float64(11), int64(5), object(20)
memory usage: 70.8+ MB
Columns
Index(['RD_NO', 'CRASH_DATE', 'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE',
       'DEVICE_CONDITION', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'FIRST_CRASH_TYPE', 'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'REPORT_TYPE', 'CRASH_TYPE',
       'DATE_POLICE_NOTIFIED', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO', 'STREET_DIRECTION',
       'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'NUM_UNITS', 'MOST_SEVERE_INJURY',
       'INJURIES_TOTAL', 'INJURIES_FATAL', 'INJURIES_INCAPACITATING',
       'INJURIES_NON_INCAPACITATING', 'INJURIES_REPORTED_NOT_EVIDENT',
       'INJURIES_NO_INDICATION', 'INJURIES_UNKNOWN', 'CRASH_HOUR',
       'CRASH_DAY_OF_WEEK', 'CRASH_MONTH', 'LATITUDE', 'LONGITUDE',
       'LOCATION'],
      dtype='object')
Shape
(257925, 36)
Missing values
RD_NO                               0
CRASH_DATE                          0
POSTED_SPEED_LIMIT                  0
TRAFFIC_CONTROL_DEVICE              0
DEVICE_CONDITION                    0
WEATHER_CONDITION                   0
LIGHTING_CONDITION                  0
FIRST_CRASH_TYPE                    0
TRAFFICWAY_TYPE                     0
ALIGNMENT                           0
ROADWAY_SURFACE_COND                0
ROAD_DEFECT                         0
REPORT_TYPE                      4996
CRASH_TYPE                          0
DATE_POLICE_NOTIFIED                0
PRIM_CONTRIBUTORY_CAUSE             0
SEC_CONTRIBUTORY_CAUSE              0
STREET_NO                           0
STREET_DIRECTION                    2
STREET_NAME                         1
BEAT_OF_OCCURRENCE                  4
NUM_UNITS                           0
MOST_SEVERE_INJURY                  7
INJURIES_TOTAL                      0
INJURIES_FATAL                      0
INJURIES_INCAPACITATING             0
INJURIES_NON_INCAPACITATING         0
INJURIES_REPORTED_NOT_EVIDENT       0
INJURIES_NO_INDICATION              0
INJURIES_UNKNOWN                    0
CRASH_HOUR                          0
CRASH_DAY_OF_WEEK                   0
CRASH_MONTH                         0
LATITUDE                         1022
LONGITUDE                        1022
LOCATION                         1022
dtype: int64
Columns with missing values
['REPORT_TYPE', 'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE', 'MOST_SEVERE_INJURY', 'LATITUDE', 'LONGITUDE', 'LOCATION']